/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using System;
using Sirenix.OdinInspector;
using Sirenix.Serialization;

namespace RosSharp.RosBridgeClient.MessageTypes.ScanningSystemCore
{
    public class ScanningGoal : Message
    {
        public const string RosMessageName = "ros_scanner_interface/ScanningGoal";

        // goal definition
        public float x1 { get; set; }
        public float y1 { get; set; }
        public float x2 { get; set; }
        public float y2 { get; set; }

        public ScanningGoal()
        {
            this.x1 = 0f;
            this.y1 = 0f;
            this.x2 = 0f;
            this.y2 = 0f;
        }

        public ScanningGoal(float x1, float y1, float x2, float y2)
        {
            this.x1 = x1;
            this.y1 = y1;
            this.x2 = x2;
            this.y2 = y2;
        }

        
        public override string ToString()
        {
            return $"p1: [{x1}, {y1}], p2: [{x2}, {y2}]";
        }
        
        public static readonly ScanningGoal DefGoal = new ScanningGoal();
    }
}
