/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.ScanningSystemCore
{
    public class StatusActionGoal : ActionGoal<StatusGoal>
    {
        public const string RosMessageName = "ros_scanner_interface/StatusActionGoal";

        public StatusActionGoal() : base()
        {
            this.goal = new StatusGoal();
        }

        public StatusActionGoal(Header header, GoalID goal_id, StatusGoal goal) : base(header, goal_id)
        {
            this.goal = goal;
        }
    }
}
