/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.RosBookSamples
{
    public class DoDishesActionResult : ActionResult<DoDishesResult>
    {
        public const string RosMessageName = "ros_book_samples/DoDishesActionResult";

        public DoDishesActionResult() : base()
        {
            this.result = new DoDishesResult();
        }

        public DoDishesActionResult(Header header, GoalStatus status, DoDishesResult result) : base(header, status)
        {
            this.result = result;
        }
    }
}
