/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RosBookSamples
{
    public class DoDishesGoal : Message
    {
        public const string RosMessageName = "ros_book_samples/DoDishesGoal";

        //  Определение цели (goal)
        public uint dishes { get; set; }
        //  Сколько мыть тарелок

        public DoDishesGoal()
        {
            this.dishes = 0;
        }

        public DoDishesGoal(uint dishes)
        {
            this.dishes = dishes;
        }
    }
}
