/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RosBookSamples
{
    public class DoDishesAction : Action<DoDishesActionGoal, DoDishesActionResult, DoDishesActionFeedback, 
                                         DoDishesGoal, DoDishesResult, DoDishesFeedback>
    {
        public const string RosMessageName = "ros_book_samples/DoDishesAction";

        public DoDishesAction() : base()
        {
            this.action_goal = new DoDishesActionGoal();
            this.action_result = new DoDishesActionResult();
            this.action_feedback = new DoDishesActionFeedback();
        }

    }
}
