/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RosBookSamples
{
    public class DoDishesResult : Message
    {
        public const string RosMessageName = "ros_book_samples/DoDishesResult";

        //  Определение результата (result)
        public uint total_dishes_cleaned { get; set; }
        //  Сколько всего было вымыто

        public DoDishesResult()
        {
            this.total_dishes_cleaned = 0;
        }

        public DoDishesResult(uint total_dishes_cleaned)
        {
            this.total_dishes_cleaned = total_dishes_cleaned;
        }
    }
}
