/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ScanningSystemCore
{
    public class ScanningAction : Action<ScanningActionGoal, ScanningActionResult, ScanningActionFeedback, ScanningGoal, ScanningResult, ScanningFeedback>
    {
        public const string RosMessageName = "scanning_system_core/ScanningAction";

        public ScanningAction() : base()
        {
            this.action_goal = new ScanningActionGoal();
            this.action_result = new ScanningActionResult();
            this.action_feedback = new ScanningActionFeedback();
        }

    }
}
