/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ScanningSystemCore
{
    public class StatusGoal : Message
    {
        public const string RosMessageName = "scanning_system_core/StatusGoal";

        // goal definition
        public bool alive { get; set; }

        public StatusGoal()
        {
            this.alive = false;
        }

        public StatusGoal(bool alive)
        {
            this.alive = alive;
        }
        
        public override string ToString()
        {
            return $"isAlive?: {alive}";
        }
        
        
        public static readonly StatusGoal DefGoal = new StatusGoal();
    }
}
