/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ScanningSystemCore
{
    public class StatusFeedback : Message
    {
        public const string RosMessageName = "ros_scanner_interface/StatusFeedback";

        // feedback
        public bool status { get; set; }

        public StatusFeedback()
        {
            this.status = false;
        }

        public StatusFeedback(bool status)
        {
            this.status = status;
        }
    }
}
