/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ScanningSystemCore
{
    public class StatusAction : Action<StatusActionGoal, StatusActionResult, StatusActionFeedback, StatusGoal, StatusResult, StatusFeedback>
    {
        public const string RosMessageName = "scanning_system_core/StatusAction";

        public StatusAction() : base()
        {
            this.action_goal = new StatusActionGoal();
            this.action_result = new StatusActionResult();
            this.action_feedback = new StatusActionFeedback();
        }

    }
}
