/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.ScanningSystemCore
{
    public class StatusResult : Message
    {
        public const string RosMessageName = "scanning_system_core/StatusResult";

        // result definition
        public bool status { get; set; }

        public StatusResult()
        {
            this.status = false;
        }

        public StatusResult(bool status)
        {
            this.status = status;
        }
    }
}
