#goal definition
shape_msgs/MeshTriangle[] triangles_CAD
geometry_msgs/Point[] vertices_CAD
geometry_msgs/PoseArray[] trajectory
int32 mode

#int32 x1
---
#result definition
shape_msgs/MeshTriangle[] triangles_CAD
geometry_msgs/Point[] vertices_CAD
geometry_msgs/Pose[] trajectory
float32 error
---
#feedback
int32 status
